name: Build-Push Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  AR_HOSTNAME: us-central1-docker.pkg.dev
  AR_REPOSITORY: teamcast-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        create_credentials_file: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.AR_HOSTNAME }}

    - name: Build and Push
      run: |
        IMAGE="${{ env.AR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/frontend"
        TAG="${GITHUB_REF_NAME:-latest}"
        docker build -t $IMAGE:$TAG -t $IMAGE:latest .
        docker push $IMAGE:$TAG
