name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  AR_HOSTNAME: asia-south1-docker.pkg.dev
  AR_REPOSITORY: oss-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
        service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        create_credentials_file: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.AR_HOSTNAME }}

    - name: Build and Push
      run: |
        IMAGE="${{ env.AR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/app"
        docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
        docker push $IMAGE:${{ github.sha }}
        docker push $IMAGE:latest 